[project]
name = "seeds"
version = "1.0.0"
requires-python = ">=3.12"
# dependencies = ["idna==3.6"] 
## Internationalized Domain Names in Applications (IDNA) vulnerable to denial of service from specially crafted inputs to idna.encode
## in idna < 3.7
dependencies = ["idna==3.7"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.uv]
managed = false
